# This is a basic workflow to help you get started with Actions

name: Make plots

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  schedule:
    - cron: 5 15 * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile:
    name: Compile COVID data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas
          python -m pip install numpy scipy matplotlib
      - shell: bash
        run: |
          python r_0_calculator.py
      - name: Upload R_0 results
        uses: actions/upload-artifact@v2
        with:
          name: knox_r_0.png
          path: knox_r_0.png
      - name: Upload cases
        uses: actions/upload-artifact@v2
        with:
          name: knox_cases.png
          path: knox_cases.png
      - name: push changes
        run: |
          git checkout master
          git config --global user.name "automated push"
          git config --global user.email "automated-github-actions@users.noreply.github.com"

          git add knox_r_0.png
          git add knox_cases.png
          git commit -m "update images"
          git push origin master
