# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile:
    name: Compile COVID data
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          python r_0_calculator.py
      - name: Upload R_0 results
        uses: actions/upload-artifact@v2
        with:
          name: knox_r_0.png
          path: knox_r_0.png
